[package]
name = "message_db"
version = "0.1.0"
authors = ["Aldo Funes <aldofunes@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-postgres = { version = "0.7.1", features = [
  "with-uuid-0_8",
  "with-chrono-0_4",
  "with-serde_json-1",
] }
tokio = { version = "1.4.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
refinery = { version = "0.5.0", features = ["tokio-postgres"] }
chrono = "0.4.19"
serde_json = "1.0.64"
log = "0.4.14"
w = "0.4.0"

[dev-dependencies]
test-context = "0.1.3"
async-trait = "0.1.48"
rand = "0.8.3"
