name: Publish Rust Crate

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    container: rust

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test
        env:
          MESSAGE_DB_CONNECTION_URI: "postgresql://postgres:postgres@postgres:5432/postgres"

      - name: Publish crate
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --dry-run
